### ISSUE TITLE
Missing connection on PCB v1.0.0

### ISSUE THREAD

**Issue by cmdzod** [romychs/54m-1#1]
Hi,

I started to build this computer and I saw that on PCB v1.0.0 pins D5/9+D6/10+D1/3 are not connected with any output. They should be connected with pin D9/9 (BK-). Also schematic must be corrected, the right signal on this must be BK-.
I was lucky because I saw your notice regarding wrong power pins for D24 and D25 before solder them, otherwise it was a good chance to lose the "magic smoke" from inside.

**Comment by romychs** [comment]
Thanks for your comment, I'll fix it soon
